name: Build
on:
  pull_request:
    paths:
      - password-checker/**
      - password-checker-backend/**

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
    strategy:
      matrix:
        step: [build,test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - name: install dependencies
        run: npm ci
      - name: run ${{ matrix.step }}
        run: npm run ${{ matrix.step }}
